### ISSUE TITLE
홈 화면 스타일 변경, 기능추가

### ISSUE THREAD

**Issue by yejify** [MusicDigging/Mudig_FE#105]
## 📝 Description
홈 화면, 스플래쉬 화면 ui 변경
홈 화면에 신규유저 플리 없을 때 ui 구현

## 🔨 To-do
- [x]  홈 화면 마이 플리 컴포넌트 배경 색 변경
- [x] 홈 화면에 신규유저 플리 없을 때 ui 구현
- [x]  스플래쉬 화면 인터렉션

## 📌 참고 사항
참고한 블로그 또는 사진 첨부
