### ISSUE TITLE
플리 상세 페이지 확인작업

### ISSUE THREAD

**Issue by dayannne** [MusicDigging/Mudig_FE#109]
## 📝 Description
누락된 기능 추가작업

## 🔨 To-do
- [ ]  모든 음악 종료 후 처리
- [ ]  댓글 이동 기능 
- [ ]  제목 말줄임 삭제?
