### ISSUE TITLE
이벤트 페이지 관련 디버깅 및 기능 추가

### ISSUE THREAD

**Issue by yejify** [MusicDigging/Mudig_FE#115]
## 📝 Description
이벤트 페이지 관련 디버깅 및 기능 추가

## 🔨 To-do
- [x]  이벤트 페이지 화면 인터렉션
- [x] 이벤트 페이지 모달 시간 제한
- [ ] 오늘 하루 안보기 버튼, 기능

## 📌 참고 사항
참고한 블로그 또는 사진 첨부
