### ISSUE TITLE
로그인/ 회원가입 사용자 개선 사항 

### ISSUE THREAD

**Issue by junny97** [MusicDigging/Mudig_FE#116]
## 📝 Description
로그인/ 회원가입 사용자 개선 사항 

## 🔨 To-do
- [ ]  이미 로그인한 유저라면 로그인/회원가입 접근 막기
- [ ]  체크박스 클릭 오류 해결 
- [ ]  이메일 인증 메일 발송 시 토스트 메시지 보여주기 

## 📌 참고 사항
참고한 블로그 또는 사진 첨부
