### ISSUE TITLE
검색 추가 수정 요청

### ISSUE THREAD

**Issue by easyxxu** [MusicDigging/Mudig_FE#119]
## 📝 Description
12.21 회의를 통해 발견한 검색 페이지의 추가 수정 목록

## 🔨 To-do
- [x] 검색창에 키워드 유지, 최근 검색어 클릭 시에도 검색창에 키워드 나오도록
- [x] 검색하고나서 뒤로가기 했을 때, 검색창에 키워드가 유지되는 문제
- [x] 추가로 검색했을 때, 검색 Nav 바 "전체"로 유지

## 📌 참고 사항
참고한 블로그 또는 사진 첨부
