### ISSUE TITLE
회원가입 페이지 구현 

### ISSUE THREAD

**Issue by junny97** [MusicDigging/Mudig_FE#13]
## 📝 Description
회원가입 페이지를 구현합니다

## 🔨 To-do
- [ ]  회원가입 시작 페이지 UI 작업
- [ ]  회원가입 디테일 페이지 UI 작업
- [ ]  회원가입 디테일 페이지 이메일,비밀번호,인증번호 유효성 검사 구현 

## 📌 참고 사항
![회원가입 - 2](https://github.com/MusicDigging/Mudig_FE/assets/72855681/25ec40be-f19d-4c27-b43a-f7cb95f46be8)
