### ISSUE TITLE
스플래쉬 QA 디버깅

### ISSUE THREAD

**Issue by yejify** [MusicDigging/Mudig_FE#136]
## 📝 Description
기능, ui 추가 디버깅

## 🔨 To-do
- [x]  토큰 인증(로그아웃 후 스플래쉬에서 로그인 페이지로 이동하도록)
- [x]  사파리에서 이미지 안보이고 팔만 보이는 문제
- [x]  배경 그라데이션 컬러가 너무 진해서 수정

## 📌 참고 사항
참고한 블로그 또는 사진 첨부
