### ISSUE TITLE
팔로우 QA 디버깅

### ISSUE THREAD

**Issue by yejify** [MusicDigging/Mudig_FE#137]
## 📝 Description
팔로우 기능 관련 디버깅

## 🔨 To-do
- [x]  아더프로필에서 팔로우 버튼, 언팔로우 버튼 기능구현
- [x]  팔로워, 팔로우 페이지 리스트 비었을 때 ui
- [x] 아더프로필에서 마이프로필로 넘어갈 때 팔로워, 팔로잉 데이터가 갱신되지 않음
- [x] 아더프로필 팔로워, 팔로잉 페이지가 내 팔로워, 팔로잉 페이지로 연결되어 있음
- [x] 이미지에 링크를 넣었더니 자동으로 display:block으로 처리되어 flex설정이 무효화됨

## 📌 참고 사항
참고한 블로그 또는 사진 첨부
