### ISSUE TITLE
유저정보 관련 리팩토링 

### ISSUE THREAD

**Issue by junny97** [MusicDigging/Mudig_FE#138]
## 📝 Description
회원가입 ,프로필 설정 등 유저정보와 관련된 부분을 고도화 합니다.

## 🔨 To-do
- [x] Toast 메시지 디자인 시안으로 변경
- [x] framer-motion 사용하여 Toast 메시지 애니메이션 효과 구현
- [x] otp post 요청코드 useMutation 사용으로 변경 
- [x]  프로필등록 post 요청코드  useMutation 사용으로 변경 

## 📌 참고 사항
참고한 블로그 또는 사진 첨부
