### ISSUE TITLE
유저정보 QA 사항 디버깅

### ISSUE THREAD

**Issue by junny97** [MusicDigging/Mudig_FE#148]
## 📝 Description
회원탈퇴시 보여줄 모달을 구현합니다
## 🔨 To-do
- [x] 회원탈퇴 모달 구현 
- [x] 탈퇴 버튼 클릭시에만 탈퇴 진행 
- [x]  탈퇴 완료후 toast메시지로 정상적으로 탈퇴했음을 알려주기 
- [x] 로그인 input 밀림 현상 해결 
- [x] 이메일 input type email로 변경
- [x] 회원가입 페이지 숫자 수정
- [x] 비밀번호 변경 시 확인 에러 메시지 수정
## 📌 참고 사항
참고한 블로그 또는 사진 첨부
