### ISSUE TITLE
리액트 라우터(Router) 설정

### ISSUE THREAD

**Issue by dayannne** [MusicDigging/Mudig_FE#15]
## 📝 Description
페이지 컴포넌트 라우터 설정하기

## 🔨 To-do

- [x]  PrivateRoute(인증된 사용자 페이지 접근) 설정
- [x]  레이아웃 컴포넌트( Header/Main/Footer ) 설정
- [x]  Router 컴포넌트 App.js로부터 분리해 설정

(기능 구현 전 일단 이렇게 틀만 미리 짜두면 좋을 것 같아 적어보았는데 추가로 좋은 아이디어 있으시면 알려주세요~!)

- 고려 사항 : Header Footer가 들어가지 않는 페이지 예외처리 (Recoil? or Route props 설정? or Header/Footer에서 예외처리?)

## 📌 참고 사항
- [PrivateRoute 구현] https://nova-68.tistory.com/125
- [레이아웃 컴포넌트] https://blog.pumpkin-raccoon.com/70 https://jae-study.tistory.com/71

**Comment by junny97** [comment]
확인했습니다 다 좋은 방법인것 같아요~

**Comment by easyxxu** [comment]
이전 프로젝트에서 레이아웃이랑 PrivateRoute 둘 다 썼었는데 어렵지 않게 할 수 있어서 적용하는거 좋은 것 같아요!

**Comment by yejify** [comment]
좋아요~ 이거 금요일 회의때 같이 해보면 좋을 거 같아요!
