### ISSUE TITLE
플리 상세 페이지 QA

### ISSUE THREAD

**Issue by dayannne** [MusicDigging/Mudig_FE#167]
## 📝 Description
간단한 설명 작성

## 🔨 To-do
- [x] 음악 재생 중 막대 가운데 px 수정
- [x] 음악 목록 없을 때 보이는 컴포넌트 가운데로 위치 수정
- [x] 댓글 필터링 기준 수정 (comments.length > 0일 때 필터링)
