### ISSUE TITLE
플리 생성 페이지 유저 피드백 반영

### ISSUE THREAD

**Issue by dayannne** [MusicDigging/Mudig_FE#176]
## 📝 Description
플리 생성 페이지 유저 피드백 반영
(추가 예정)

## 🔨 To-do
- [x] ~~3페이지 인풋 엔터 키다운 이벤트 막기~~
- [x] ~~최대 3개까지 선택 가능 문구 추가~~
- [x] 연도 선택 input창 -> input radio태그 버튼으로 변경
- [x] 장르 선택 1개로 제한 (button -> input radio태그 버튼으로 변경)
