### ISSUE TITLE
프로필&프로필 수정 페이지 변경된 UI 디자인 반영

### ISSUE THREAD

**Issue by dayannne** [MusicDigging/Mudig_FE#178]
## 📝 Description
프로필&프로필 수정 페이지 변경된 UI 디자인 반영

## 🔨 To-do
- [x]  프로필 이미지 UI 변경
- [x] 기본 프로필 이미지 변경된 디자인으로 보이도록 필터링  
  <img width="211" alt="image" src="https://github.com/MusicDigging/Mudig_FE/assets/105140201/acdf3572-8bfb-489b-b3c6-ffd0a21455fa">
- [x]  프로필 수정 - 관심사 3개 선택 문구 추가
- [x] 대표 플레이리스트 설정 - 플리 없을 때 bordot-bottom 삭제
