### ISSUE TITLE
프로필&프로필 수정 페이지 유저 피드백 반영

### ISSUE THREAD

**Issue by dayannne** [MusicDigging/Mudig_FE#179]
## 📝 Description
프로필&프로필 수정 페이지 유저 피드백 반영
(피드백 받는대로 추가 예정)

## 🔨 To-do
- [x]  프로필 수정에서 닉네임 변경 후 메인 페이지에서 변경된 닉네임 적용
- [x] 대표 플레이리스트 설정 조건 수정, 데이터 변경 (myplaylist)
- [x] 팔로우 버튼 글자 줄바꿈되는 부분 수정
