### ISSUE TITLE
유저정보 관련 유저 피드백 반영

### ISSUE THREAD

**Issue by junny97** [MusicDigging/Mudig_FE#182]
## 📝 Description
유저정보와 관련된 유저 피드백 내용들을 반영하여 수정합니다 

## 🔨 To-do
- [x] 유저정보 관련 입력 input의 자동완성 해제하기 
- [x] 프로필 설정 시 기본적으로 관심사는 3개까지 설정할 수 있다고 알려주기
- [x]  아이디 비밀번호 찾기 기능 미구현 상태임을 알려주기
- [x] input 포커싱 시 확대되는 문제 고치기 
## 📌 참고 사항
참고한 블로그 또는 사진 첨부
[[iOS/Safari] <input />의 focus 확대 방지하기](https://velog.io/@jungsu/iOSSafari-input-%EC%9D%98-focus-%ED%99%95%EB%8C%80-%EB%B0%A9%EC%A7%80%ED%95%98%EA%B8%B0)
