### ISSUE TITLE
프로필 설정 페이지 구현

### ISSUE THREAD

**Issue by junny97** [MusicDigging/Mudig_FE#19]
## 📝 Description
프로필 설정 페이지를 구현합니다.

## 🔨 To-do
- [x]  프로필 설정 페이지 UI 작업
- [x] imageCompression 라이브러리 사용하여 이미지 등록시 압축 진행 &  이미지 압축 함수 분리
- [x]  프로필 입력 폼 UI 작업 & 닉네임 8글자 제한 유효성 검사 구현
- [ ] Chip 컴포넌트 생성 후 ChipButton 적용 

## 📌 참고 사항
![프로필 설정](https://github.com/MusicDigging/Mudig_FE/assets/72855681/bf7fa5cd-0c50-4d4e-b1a2-99fc2ef2baa9)
