### ISSUE TITLE
홈페이지 유저 피드백 반영

### ISSUE THREAD

**Issue by yejify** [MusicDigging/Mudig_FE#191]
## 📝 Description
유저 피드백 내용 반영
디자인 변경사항 반영

## 🔨 To-do
- [x]  유저 닉네임 변경 후 메인페이지 적용 안됨 -> 프로필 수정 후 userInfo 업데이트
- [x]  플리 여백 다름 -> 디자인상 여백이 다르게 설정 됨
- [x]  메인 페이지 폰트 계층이 확실했으면 좋겠음 -> 디자인 변경 없음
- [x] 메인 각각의 플리 상세 페이지가 있으면 좋겠음
- [x] 에러 페이지 디자인 변경

## 📌 참고 사항
참고한 블로그 또는 사진 첨부
