### ISSUE TITLE
플리 생성 페이지 구현

### ISSUE THREAD

**Issue by dayannne** [MusicDigging/Mudig_FE#21]
## 📝 Description
플리 생성 페이지  UI 구현

## 🔨 To-do
feature/NewPlaylist/Create에서 작업
총 3개의 플리생성 페이지, Link 태그로 전환
- [x]  캐릭터 이미지 삽입 
- [x]  답변 입력창(textarea) : height 길이 자동조절 기능 넣기 `react-textarea-autosize`라이브러리 활용
- [x] 라우터 페이지 전환 애니메이션 고려 : framer-motion 라이브러리 사용

(고려 사항) : 캐릭터 이미지 애니메이션 구현 여부 

## 📌 참고 사항
[react-textarea-autosize라이브러리](https://www.npmjs.com/package/react-textarea-autosize?activeTab=readme)
[react-textarea-autosize라이브러리 활용 방법](https://velog.io/@yeonsubaek/React-textarea-%EC%A4%84%EB%B0%94%EA%BF%88%EC%97%90-%EB%94%B0%EB%9D%BC-%EB%86%92%EC%9D%B4-%EC%A1%B0%EC%A0%88%ED%95%98%EA%B8%B0-feat.-react-textarea-autosize?utm_source=oneoneone
)
[framer-motion 라이브러리](https://velog.io/@tai/React-%ED%8E%98%EC%9D%B4%EC%A7%80-%EC%A0%84%ED%99%98-%EC%95%A0%EB%8B%88%EB%A9%94%EC%9D%B4%EC%85%98%EC%9D%84-%EC%9C%84%ED%95%9C-framer-motion)

![플리생성](https://github.com/MusicDigging/Mudig_FE/assets/105140201/31fe824e-0def-46cb-8bb2-60309063f70c)
