### ISSUE TITLE
Main Outlet, PrivateRoute 리팩토링

### ISSUE THREAD

**Issue by yejify** [MusicDigging/Mudig_FE#228]
## 📝 Description
PrivateRoute, EventPage, Home, MorePlaylist 페이지 리팩토링

## 🔨 To-do

전체
- [x] 불필요한 인터페이스 제거, 타입 선언 제거
- [x] 주석, 클래스, 사용 안하는 코드 제거
- [x] ul안에 li안에 a요소 넣기

홈
- [x] playListTable에 제목, 더보기 버튼 추가
- [x] morePlaylist switch사용해서 컴포넌트화
- [x] url state에 담에서useLocation으로 가져오기

이벤트 페이지
- [x] useMutation hook 분리

## 📌 참고 사항
해당 코드와 함께 댓글에 리팩토링 사항 적기

**Comment by junny97** [comment]
https://github.com/MusicDigging/Mudig_FE/blob/0c0393c45e754d86a33e77070e1d7f8f48a416b9/src/pages/EventPage/EventPage.tsx#L9
https://github.com/MusicDigging/Mudig_FE/blob/0c0393c45e754d86a33e77070e1d7f8f48a416b9/src/pages/EventPage/EventPage.tsx#L25-L44

API 통신 로직 React Query  ```const { data, isLoading } = useQuery``` useQuery 훅 사용으로 변경해서 isLoading 
 메소드 사용하면 isLoading 상태 굳이 설정할 필요 없으니 변경하는것이 좋다 생각해

**Comment by junny97** [comment]
https://github.com/MusicDigging/Mudig_FE/blob/b81978c436816f39a0264cb0e8a27c65c1b18595/src/pages/Home/Home.tsx#L13-L19
IHomeData 선언되었지만 사용되는 곳이 없어서 사용하지 않는 인터페이스라면 삭제하는게 좋을것 같아

**Comment by easyxxu** [comment]
**홈**
https://github.com/MusicDigging/Mudig_FE/blob/b81978c436816f39a0264cb0e8a27c65c1b18595/src/pages/Home/Home.tsx#L49
- aria-label='더보기' 추가 (접근성)
  - 해당 파일 MoreBtn에 전부 적용


https://github.com/MusicDigging/Mudig_FE/blob/b81978c436816f39a0264cb0e8a27c65c1b18595/src/pages/Home/Home.tsx#L44-L91
<img width="423" alt="스크린샷 2024-03-05 오후 2 46 09" src="https://github.com/MusicDigging/Mudig_FE/assets/107910342/6da2aceb-5b31-4260-a75e-25f240fd24ff">
- (사진처럼 하나의) 컴포넌트로 만들어 재사용하는 것도 좋은 방법

https://github.com/MusicDigging/Mudig_FE/blob/b81978c436816f39a0264cb0e8a27c65c1b18595/src/components/common/Header/MainHeader.tsx#L7-L19
- 타입처리 안해도 됨 -> export default function MainHeader() { ... }
- self-closing tag인 img 태그는 바로 닫기 `<img src=... />`
- `<Search />`에도 aria-label 적용해주기

https://github.com/MusicDigging/Mudig_FE/blob/b81978c436816f39a0264cb0e8a27c65c1b18595/src/components/Home/PlayListTable.tsx#L25-L45
- ul>a>li (X) => ul>li>a (O)

https://github.com/MusicDigging/Mudig_FE/blob/b81978c436816f39a0264cb0e8a27c65c1b18595/src/components/common/NavBar/NavBar.tsx#L9-L51
- 타입처리 안해도 됨 -> export default function NavBar() { ... }
- ul>a>li (X) => ul>li>a (O)

https://github.com/MusicDigging/Mudig_FE/blob/b81978c436816f39a0264cb0e8a27c65c1b18595/src/components/Home/MyPlayListTable.tsx#L22-L41
- li 태그 추가 필요

https://github.com/MusicDigging/Mudig_FE/blob/b81978c436816f39a0264cb0e8a27c65c1b18595/src/components/Home/MyPlayListTable.tsx#L47-L54
- background-color: transparent 오타 (근데 설정안해도 되는 듯)
- display: flex 관련 스타일 제거 (PlayListBox에도 flex가 적용되어 있어서)

https://github.com/MusicDigging/Mudig_FE/blob/b81978c436816f39a0264cb0e8a27c65c1b18595/src/pages/Home/MorePlaylist.tsx#L25-L61
- 컴포넌트로 만들어 재사용 증가, 가독성 개선하기
- 예시
  ```js
  // 컴포넌트 공통 렌더링 로직
    const renderCommonContent = (title: string) => (
      <S.MorePlaylistWrap>
        <S.BackButton onClick={() => navigate(-1)}></S.BackButton>
        <h2 className='morePlaylistName'>{title}</h2>
        <MyPlayListTable playlistData={playlistData} />
      </S.MorePlaylistWrap>
    );
  
    // 데이터 불러오기 또는 컴포넌트 선택을 위한 로직
    let content;
    switch (playlistType) {
      case 'recommend':
        content = renderCommonContent(`${userInfo.name}님을 위한 플레이리스트`);
        break;
      case 'hot':
        content = renderCommonContent('지금 핫한🔥 플레이리스트');
        break;
      case 'new':
        content = renderCommonContent('신규 플레이리스트');
        break;
      default:
        content = <NotFound />;
    }
  ```

**Comment by easyxxu** [comment]
**이벤트 페이지**
https://github.com/MusicDigging/Mudig_FE/blob/b81978c436816f39a0264cb0e8a27c65c1b18595/src/pages/EventPage/EventPage.tsx#L47-L71
- input 태그도 self-closing tag

**Comment by dayannne** [comment]
- data를 url에 넣어 보내면서 url이 너무 길어지는 문제
https://github.com/MusicDigging/Mudig_FE/blob/b81978c436816f39a0264cb0e8a27c65c1b18595/src/pages/Home/Home.tsx#L35-L39
   ```
  http://localhost:3000/main/hot?data=%5B%7B%22id%22%3A16%2C%22like_count%22%3A7%2C%22like_playlist%22%3Afalse%2C%22title%22%3A%22%F0%9F%8F%B5%EF%B8%8F%20%EC%95%84%EC%9D%B4%EB%AC%AD%EC%9D%98%20%EC%95%84%EB%A6%84%EB%8B%A4%EC%9A%B4%20%EC%9D%8C%EC%95%85%20%EC%97%AC%EC%A0%95%22%2C%22content%22%3A%22%EC%9D%B4%20%ED%94%8C%EB%A0%88%EC%9D%B4%EB%A6%AC%EC%8A%A4%ED%8A%B8%EB%8A%94%202017%EB%85%84%EB%B6%80%ED%84%B0%20%ED%98%84%EC%9E%AC%EA%B9%8C%EC%A7%80%EC%9D%98%20%EC%95%84%EC%9D%B4%EB%AC%AD%EC%9D%98%20%EA%B0%90%EC%84%B1%EC%A0%81%EC%9D%B8%20%EC%9D%8C%EC%95%85%EC%9D%84%20%EB%8B%B4%EA%B3%A0%20%EC%9E%88%EC%8A%B5%EB%8B%88%EB%8B%A4.%20%EC%95%84%EC%9D%B4%EB%AC%AD%EC%9D%98%20%EC%9D%BC%EB%A0%89%ED%8A%B8%EB%A1%9C%EB%8B%89%20%EC%82%AC%EC%9A%B4%EB%93%9C%EC%99%80%20%EC%9D%B8%EB%94%94%20%EA%B0%90%EC%84%B1%EC%9D%B4%20%EC%96%B4%EC%9A%B0%EB%9F%AC%EC%A0%B8%20%EC%97%AC%EB%9F%AC%EB%B6%84%EC%9D%98%20%EB%A7%88%EC%9D%8C%EC%9D%84%20%ED%9D%94%EB%93%A4%20%EA%B2%83%EC%9E%85%EB%8B%88%EB%8B%A4.%20%ED%8E%B8%EC%95%88%ED%95%98%EA%B2%8C%20%EC%A6%90%EA%B8%B0%EC%84%B8%EC%9A%94!!!%22%2C%22thumbnail%22%3A%22karlo%2F41e76376a08a11eeae840700a75bb434%22%2C%22genre%22%3A%22J-POP%2C%EC%9D%B8%EB%94%94%2CPOP%22%2C%22is_active%22%3Atrue%2C%22created_at%22%3A%222023-12-22T14%3A23%3A36.961757%2B09%3A00%22%2C%22updated_at%22%3A%222024-01-02T23%3A34%3A20.328824%2B09%3A00%22%2C%22is_public%22%3Atrue%2C%22writer%22%3A6%2C%22music%22%3A%5B65%2C66%2C68%2C160%2C526%2C527%5D%7D%2C%7B%22id%22%3A23%2C%22like_count%22%3A4%2C%22like_playlist%22%3Afalse%2C%22title%22%3A%22%E2%9C%A8%20KPOP%20%EC%97%AC%EC%9E%90%20%EC%95%84%EC%9D%B4%EB%8F%8C%EC%9D%98%20%ED%99%9C%EB%A0%A5%20%EB%84%98%EC%B9%98%EB%8A%94%20%EB%85%B8%EB%9E%98%EB%AA%A8%EC%9D%8C%22%2C%22content%22%3A%22%EC%9D%B4%20%ED%94%8C%EB%A0%88%EC%9D%B4%EB%A6%AC%EC%8A%A4%ED%8A%B8%EB%8A%94%202020%EB%85%84%EB%B6%80%ED%84%B0%20%ED%98%84%EC%9E%AC%EA%B9%8C%EC%A7%80%EC%9D%98%20%EC%9D%B8%EA%B8%B0%20K-POP%20%EC%97%AC%EC%9E%90%20%EC%95%84%EC%9D%B4%EB%8F%8C%EC%9D%98%20%ED%99%9C%EB%A0%A5%20%EB%84%98%EC%B9%98%EB%8A%94%20%EB%85%B8%EB%9E%98%EB%93%A4%EB%A1%9C%20%EA%B5%AC%EC%84%B1%EB%90%98%EC%96%B4%20%EC%9E%88%EC%8A%B5%EB%8B%88%EB%8B%A4.%20%EC%97%85%ED%85%90%EC%85%98%EA%B3%BC%20%ED%9D%A5%EB%AF%B8%EB%A5%BC%20%EC%A3%BC%EB%8A%94%20%EB%A6%AC%EB%93%AC%EA%B3%BC%20%EA%B0%95%EB%A0%AC%ED%95%9C%20%EB%B3%B4%EC%BB%AC%EB%A1%9C%20%EC%97%AC%EB%9F%AC%EB%B6%84%EC%9D%98%20%EA%B8%B0%EB%B6%84%EC%9D%84%20%EC%97%85%EA%B7%B8%EB%A0%88%EC%9D%B4%EB%93%9C%ED%95%B4%EC%A4%84%20%EA%B2%83%EC%9E%85%EB%8B%88%EB%8B%A4.%20%EC%A6%90%EA%B2%81%EA%B2%8C%20%EA%B0%90%EC%83%81%ED%95%98%EC%84%B8%EC%9A%94!%22%2C%22thumbnail%22%3A%22karlo%2F6c74aaf8a08b11eeae840700a75bb434%22%2C%22genre%22%3A%22K-POP%22%2C%22is_active%22%3Atrue%2C%22created_at%22%3A%222023-12-22T14%3A31%3A57.895432%2B09%3A00%22%2C%22updated_at%22%3A%222024-01-02T23%3A20%3A34.593927%2B09%3A00%22%2C%22is_public%22%3Atrue%2C%22writer%22%3A6%2C%22music%22%3A%5B15%2C84%2C85%2C86%2C87%5D%7D%2C%7B%22id%22%3A90%2C%22like_count%22%3A4%2C%22like_playlist%22%3Afalse%2C%22title%22%3A%22%EC%9A%B4%EB%8F%99%ED%95%A0%20%EB%95%8C%20%EB%93%A3%EA%B8%B0%20%EC%A2%8B%EC%9D%80%20J-pop%20%ED%94%8C%EB%A0%88%EC%9D%B4%EB%A6%AC%EC%8A%A4%ED%8A%B8%22%2C%22content%22%3A%22%EC%9D%B4%20%ED%94%8C%EB%A0%88%EC%9D%B4%EB%A6%AC%EC%8A%A4%ED%8A%B8%EB%8A%94%20%EC%9A%B4%EB%8F%99%ED%95%A0%20%EB%95%8C%20%EB%93%A3%EA%B8%B0%20%EC%A2%8B%EC%9D%80%20J-pop%20%EC%9D%8C%EC%95%85%EB%93%A4%EB%A1%9C%20%EA%B5%AC%EC%84%B1%EB%90%98%EC%96%B4%20%EC%9E%88%EC%8A%B5%EB%8B%88%EB%8B%A4.%20%EA%B0%95%EB%A0%AC%ED%95%9C%20%EB%A6%AC%EB%93%AC%EA%B3%BC%20%EC%97%90%EB%84%88%EC%A7%80%20%EB%84%98%EC%B9%98%EB%8A%94%20%EB%A9%9C%EB%A1%9C%EB%94%94%EA%B0%80%20%EC%9A%B4%EB%8F%99%20%EB%8F%99%EC%95%88%20%EB%8F%99%EA%B8%B0%EB%B6%80%EC%97%AC%EB%A5%BC%20%EC%A4%84%20%EA%B2%83%EC%9E%85%EB%8B%88%EB%8B%A4.%20%ED%9E%98%EC%B0%A8%EA%B2%8C%20%EC%9A%B4%EB%8F%99%ED%95%B4%EB%B3%B4%EC%84%B8%EC%9A%94!%22%2C%22thumbnail%22%3A%22karlo%2Fb3ba3ea0a63a11eeae840700a75bb434%22%2C%22genre%22%3A%22J-POP%22%2C%22is_active%22%3Atrue%2C%22created_at%22%3A%222023-12-29T20%3A09%3A15.171032%2B09%3A00%22%2C%22updated_at%22%3A%222023-12-29T20%3A09%3A15.171051%2B09%3A00%22%2C%22is_public%22%3Atrue%2C%22writer%22%3A67%2C%22music%22%3A%5B70%2C71%2C71%2C73%2C74%5D%7D%2C%7B%22id%22%3A55%2C%22like_count%22%3A3%2C%22like_playlist%22%3Afalse%2C%22title%22%3A%22%EB%88%88%20%EC%98%AC%20%EB%95%8C%20%EC%A6%90%EA%B8%B0%EB%8A%94%20K-POP%20%ED%94%8C%EB%A0%88%EC%9D%B4%EB%A6%AC%EC%8A%A4%ED%8A%B8%22%2C%22content%22%3A%22%EB%88%88%EC%9D%B4%20%EB%82%B4%EB%A6%AC%EB%8A%94%20%EB%82%A0%EC%97%90%20%EC%96%B4%EC%9A%B8%EB%A6%AC%EB%8A%94%20K-POP%20%ED%94%8C%EB%A0%88%EC%9D%B4%EB%A6%AC%EC%8A%A4%ED%8A%B8%EC%9E%85%EB%8B%88%EB%8B%A4.%20%EC%9D%B4%20%EC%9D%8C%EC%95%85%EB%93%A4%EC%9D%80%202020%EB%85%84%EC%97%90%20%EB%B0%9C%EB%A7%A4%EB%90%9C%20%EA%B3%A1%EC%9C%BC%EB%A1%9C%2C%20%EA%B0%81%EA%B0%81%EC%9D%98%20%ED%8A%B9%EC%83%89%EA%B3%BC%20%EB%A9%9C%EB%A1%9C%EB%94%94%EA%B0%80%20%EB%88%88%20%EB%82%B4%EB%A6%AC%EB%8A%94%20%EC%88%9C%EA%B0%84%EC%9D%98%20%EC%95%84%EB%8A%91%ED%95%98%EA%B3%A0%20%EB%A1%9C%EB%A7%A8%ED%8B%B1%ED%95%9C%20%EB%B6%84%EC%9C%84%EA%B8%B0%EB%A5%BC%20%EB%8D%94%ED%95%B4%EC%A4%84%20%EA%B2%83%EC%9E%85%EB%8B%88%EB%8B%A4.%20%EB%88%88%EC%9D%84%20%EB%B0%94%EB%9D%BC%EB%B3%B4%EB%A9%B0%20%EC%9D%B4%20%EC%9D%8C%EC%95%85%EC%9D%84%20%EC%A6%90%EA%B2%A8%EB%B3%B4%EC%84%B8%EC%9A%94!%22%2C%22thumbnail%22%3A%22karlo%2Fb37bd162a3ef11eeae840700a75bb434%22%2C%22genre%22%3A%22K-POP%22%2C%22is_active%22%3Atrue%2C%22created_at%22%3A%222023-12-26T22%3A07%3A20.227445%2B09%3A00%22%2C%22updated_at%22%3A%222024-01-10T23%3A02%3A44.780174%2B09%3A00%22%2C%22is_public%22%3Atrue%2C%22writer%22%3A5%2C%22music%22%3A%5B195%2C197%2C198%2C199%2C196%2C43%2C299%2C22%2C4%2C118%2C16%5D%7D%2C%7B%22id%22%3A93%2C%22like_count%22%3A3%2C%22like_playlist%22%3Afalse%2C%22title%22%3A%22%EB%B0%A4%EC%83%98%20%EC%9E%91%EC%97%85%EC%9D%84%20%EC%9C%84%ED%95%9C%20%ED%9D%A5%EB%82%98%EB%8A%94%20J-POP%20%ED%94%8C%EB%A0%88%EC%9D%B4%EB%A6%AC%EC%8A%A4%ED%8A%B8%22%2C%22content%22%3A%22%EC%9E%91%EC%97%85%EC%9D%84%20%EB%8D%94%EC%9A%B1%20%ED%9D%A5%EA%B2%A8%EC%9A%B4%20%EB%B6%84%EC%9C%84%EA%B8%B0%EC%97%90%EC%84%9C%20%EC%A7%84%ED%96%89%ED%95%98%EA%B3%A0%20%EC%8B%B6%EB%8B%A4%EB%A9%B4%20%EC%9D%B4%20%ED%94%8C%EB%A0%88%EC%9D%B4%EB%A6%AC%EC%8A%A4%ED%8A%B8%EB%A5%BC%20%EB%93%A4%EC%96%B4%EB%B3%B4%EC%84%B8%EC%9A%94.%20Official%20HIGE%20DANDism%EA%B3%BC%20%E7%B1%B3%E6%B4%A5%E7%8E%84%E5%B8%AB%20%EB%93%B1%EC%9D%98%20J-POP%20%EC%95%84%ED%8B%B0%EC%8A%A4%ED%8A%B8%EB%93%A4%EC%9D%98%20%ED%9E%88%ED%8A%B8%20%EA%B3%A1%EB%93%A4%EB%A1%9C%20%EA%B0%80%EB%93%9D%20%EC%B0%A8%20%EC%9E%88%EC%8A%B5%EB%8B%88%EB%8B%A4.%20%EC%9E%91%EC%97%85%EC%97%90%20%EC%A7%91%EC%A4%91%ED%95%98%EB%A9%B4%EC%84%9C%20%EC%A6%90%EA%B1%B0%EC%9B%80%EC%9D%84%20%EB%8A%90%EB%82%84%20%EC%88%98%20%EC%9E%88%EC%9D%84%20%EA%B2%83%EC%9E%85%EB%8B%88%EB%8B%A4!%22%2C%22thumbnail%22%3A%22karlo%2Fc2c51ab8a63b11eeae840700a75bb434%22%2C%22genre%22%3A%22J-POP%22%2C%22is_active%22%3Atrue%2C%22created_at%22%3A%222023-12-29T20%3A16%3A49.933760%2B09%3A00%22%2C%22updated_at%22%3A%222023-12-29T20%3A16%3A49.933781%2B09%3A00%22%2C%22is_public%22%3Atrue%2C%22writer%22%3A68%2C%22music%22%3A%5B71%2C234%2C301%2C302%2C303%5D%7D%5D
   ```
   state에 담아 보내고 useLocation으로 받아오는 형식은 어떨지
예시)
  ```tsx
    const handleMoreClick = (playlistType: string, data: IPlaylist[]) => {
      navigate(`/main/${playlistType}`, {
        state: { data: data },
      });
    };
  ```
  ```tsx
    const location = useLocation()
    const state = location?.state
    // 두 버전
   // const { data: playlistData } = state;
   // const playlistData = state ? state?.data : null;
  ```

- liSize 내 props가 width만 쓰이고 있는 것 같아서 추가할 게 아니라면 객체 형식의 할당 말고 `liWidth = '152px'`로 바로 넘겨줘도 될 것 같음
https://github.com/MusicDigging/Mudig_FE/blob/b81978c436816f39a0264cb0e8a27c65c1b18595/src/pages/Home/Home.tsx#L51-L54
  예시)
  ```tsx
    <PlayListTable
      liWidth = '152px' 
      playlistData={recommend_pli}
    />
  
  // ...
  
  const ImageBox = styled.div<{ liWidth : string}>`
    width: ${(props) => props.liWidth };
    height: ${(props) => props.liWidth };
    border-radius: 8px;
  `;
  ```
  ```
  interface ILiSize {
    width: string;
  }
  ```
  그러면 위 인터페이스 정의 안해도 될 듯!
- 불필요한 className 삭제https://github.com/MusicDigging/Mudig_FE/blob/b81978c436816f39a0264cb0e8a27c65c1b18595/src/components/Home/PlayListTable.tsx#L24

- 아래 API 요청 useMutaion 훅으로 분리
https://github.com/MusicDigging/Mudig_FE/blob/b81978c436816f39a0264cb0e8a27c65c1b18595/src/pages/EventPage/EventPage.tsx#L25-L44

- 사용되지 않는 값 삭제
https://github.com/MusicDigging/Mudig_FE/blob/b81978c436816f39a0264cb0e8a27c65c1b18595/src/pages/EventPage/EventPage.tsx#L10
