### ISSUE TITLE
RandomMusic, CreatePlaylist1~3, PlaylistSummary 리팩토링

### ISSUE THREAD

**Issue by junny97** [MusicDigging/Mudig_FE#231]
## 📝 Description
간단한 설명 작성

## 🔨 To-do
 - [ ] import 사용 안하는 거삭제
 - [ ] console.log 삭제
 - [ ]  style component 분리
## 📌 참고 사항
참고한 블로그 또는 사진 첨부

**Comment by yejify** [comment]
https://github.com/MusicDigging/Mudig_FE/blob/8411f0ec21bbde7f14c2573efc12d89316ac403f/src/pages/RandomMusic/RandomMusic.tsx#L32-L53

fetchRandomMv 함수를 useEffect 밖에서 정의하고 의존성 배열에 추가해서 변화가 감지 될 때마다 함수를 재생성 하지 않고 로직이 실행되도록 하면 성능 개선에 도움이 되지 않을까?
근데 그러다가 오류 날까봐 좀 걱정이 되긴 한다..

**Comment by yejify** [comment]
https://github.com/MusicDigging/Mudig_FE/blob/8411f0ec21bbde7f14c2573efc12d89316ac403f/src/pages/CreatePlaylist/CreatePlaylist3.tsx#L19-L21

가독성 향상을 위해 중복 조건으로 정의하는 대신 아래와 같이 코드를 바꾸는 건 어떨까?
```
const { situations, genre, year: initialYear = '' } = location.state || {};
const [year, setYear] = useState(initialYear);
```
