### ISSUE TITLE
Profile, Follow, EditProfile, ChangePassword, Resign 리팩토링

### ISSUE THREAD

**Issue by yejify** [MusicDigging/Mudig_FE#232]
## 📝 Description
간단한 설명 작성

## 🔨 To-do

- [ ]  import 사용 안하는 거삭제
- [ ]  console.log 삭제
- [ ]  style component 분리

## 📌 참고 사항
참고한 블로그 또는 사진 첨부

**Comment by dayannne** [comment]
- 어디에 쓰이는 지 모르겠는..? 변수 삭제
https://github.com/MusicDigging/Mudig_FE/blob/f3a70c6aef88dad7b6424bb895840fd51c17d920/src/pages/Profile/Follow.tsx#L31
https://github.com/MusicDigging/Mudig_FE/blob/f3a70c6aef88dad7b6424bb895840fd51c17d920/src/pages/Profile/Follow.tsx#L40-L52

- 사용하지 않는 타입
https://github.com/MusicDigging/Mudig_FE/blob/f3a70c6aef88dad7b6424bb895840fd51c17d920/src/pages/Profile/Follow.tsx#L80

- `data.map(transformUserData)` 이 곧 `data` 같은데유....??? `userDataProps`, `transformUserData` 삭제해도 될 듯
https://github.com/MusicDigging/Mudig_FE/blob/f3a70c6aef88dad7b6424bb895840fd51c17d920/src/pages/Profile/Follow.tsx#L78-L105
https://github.com/MusicDigging/Mudig_FE/blob/f3a70c6aef88dad7b6424bb895840fd51c17d920/src/pages/Profile/Follow.tsx#L15-L20
  ```tsx
  // 변경 전
       users={data.map(transformUserData)}
  // 변경 후
       users={data}
  ```

---

**아래는 UserLeaveForm, ChangePwForm 동시 해당되는 내용!**

- regex 분리
https://github.com/MusicDigging/Mudig_FE/blob/f3a70c6aef88dad7b6424bb895840fd51c17d920/src/pages/UserInfo/ChangePwForm.tsx#L24

- `===` 사용
https://github.com/MusicDigging/Mudig_FE/blob/f3a70c6aef88dad7b6424bb895840fd51c17d920/src/pages/UserInfo/ChangePwForm.tsx#L135

- useSetRecoilState 대신 `useResecRecoilState` 사용해 보는 건 어떨지..?? atom 값을 디폴트 값으로 변경시켜주는 친구
변경 전
https://github.com/MusicDigging/Mudig_FE/blob/f3a70c6aef88dad7b6424bb895840fd51c17d920/src/pages/UserInfo/ChangePwForm.tsx#L22
https://github.com/MusicDigging/Mudig_FE/blob/f3a70c6aef88dad7b6424bb895840fd51c17d920/src/pages/UserInfo/ChangePwForm.tsx#L47-L59
변경 후
  ```tsx
    const resetUserInfo= useResetRecoilState(userInfoAtom);
  ```
  ```tsx
    resetUserInfo();
  ```

**Comment by easyxxu** [comment]
https://github.com/MusicDigging/Mudig_FE/blob/f91373e30abcb4f7729165082157a071d03a1332/src/components/Profile/FollowUserList.tsx#L23-L34
- 리스트에서 아이템이 많아지면 스크롤 되도록 처리하기

https://github.com/MusicDigging/Mudig_FE/blob/f91373e30abcb4f7729165082157a071d03a1332/src/components/Profile/ProfileSection.tsx#L32-L34
```
const handleMoreBtnClick = () => setIsModalOpen(!isModalOpen);
```
- 더 간단히 수정가능
