### ISSUE TITLE
플리 상세/수정 페이지 구현

### ISSUE THREAD

**Issue by dayannne** [MusicDigging/Mudig_FE#33]
## 📝 Description
플리 상세/수정 페이지 UI 구현
`feature/PlaylistDetail` 브랜치에서 작업

## 🔨 To-do
- [x]  댓글 UI
- [x]  댓글 입력 form UI
- [x]  썸네일 + 상세 설명 UI
- [x] 플리 목록 (버튼 누르면 전체 목록 보이도록)
- [x] 플리 목록 순서 수정
- [x] 동영상 UI - `react-player` 라이브러리 활용
- [x] 재생바 + 공유, 더보기 버튼 UI 
- [x] 더보기 버튼 클릭시 활성화되는 모달 UI
- [ ] 플리 수정 모달
## 📌 참고 사항
<img width="672" alt="스크린샷 2023-11-28 오후 3 36 36" src="https://github.com/MusicDigging/Mudig_FE/assets/107910342/feb403a1-6866-401e-af6f-73a461794f87">
