### ISSUE TITLE
로그인/회원가입 최종 디자인 확인작업

### ISSUE THREAD

**Issue by junny97** [MusicDigging/Mudig_FE#36]
## 📝 Description
기존의 구현한 로그인 회원가입 UI와 최종 디자인 UI를 비교하며 변경된 사항을 확인하고 수정합니다.

## 🔨 To-do
- [ ]  중복되는 css 속성 제거
- [ ] 컬러색 확인하기
- [ ]  비밀번호 보기 / 숨기기 위치 통일
- [ ]  회원가입 약관 footer 삭제
- [ ] 로그인 회원가입 프로필 설정 패아자 Rotuer 연결

## 📌 참고 사항
참고한 블로그 또는 사진 첨부
