### ISSUE TITLE
생성 요약 페이지 구현

### ISSUE THREAD

**Issue by easyxxu** [MusicDigging/Mudig_FE#43]
## 📝 Description
생성 요약 페이지 구현

## 🔨 To-do
- [ ] 플리 공개 여부 설정 컴포넌트
- [ ] 화면 하단 블러 스타일 적용
- [ ] PlayListInfo 타이틀 다르게 처리
- [ ] 플레이리스트

## 📌 참고 사항
![생성 요약](https://github.com/MusicDigging/Mudig_FE/assets/107910342/59671d4b-7b5b-45b2-b9b7-cafe64e4ab4d)
