### ISSUE TITLE
프로필 설정 페이지 기능구현

### ISSUE THREAD

**Issue by junny97** [MusicDigging/Mudig_FE#51]
## 📝 Description
프로필 설정 페이지 기능구현을 진행하여 회원가입에서 받아온 이메일과 비밀번호와 함께 유저 정보를 설정합니다.

## 🔨 To-do
- [x] 회원가입시 설정한 email, password 정보 받아오기
- [x] 프로필 설정 이미지 미리보기, 이미지 압축 진행
- [x] 유저 닉네임 입력시 입력한 닉네임 유효성 검사 진행
- [x]  최대 관심사 3개까지 선택할 수 있게 설정 & 선택한 관심사 문자열로 변환
- [x] 닉네임 유효성 검사 통과시에는 통과 메시지, 실패시에는 실패 메시지 보여주기
- [x] 닉네임 작성, 장르  chip 버튼 하나라도 선택해야만 form 제출 허용
- [x] email, password, name ,about, genre, image form submit 이벤트로 post 요청 보내기 
- [x] 유저 atom 파일에 정보 업데이트
- [x] 유저가 입력한 닉네임 중복검사 post 요청시에 디바운싱 1초 설정하기 

## 📌 참고 사항
참고한 블로그 또는 사진 첨부
