### ISSUE TITLE
검색 페이지 기능 구현

### ISSUE THREAD

**Issue by easyxxu** [MusicDigging/Mudig_FE#57]
## 📝 Description
검색 페이지 기능 구현

## 🔨 To-do
- [x] 검색 페이지 API 연결
- [x] 검색 결과 user, playlist로 나누어서 출력
- [x] 최근 검색어
- [x] 최근 검색어 전체 삭제
- [x] 최근 검색어 선택 삭제
- [x] 플리, 유저 클릭 시 페이지 이동
- [x] react-query로 수정
