### ISSUE TITLE
플리 생성 페이지 기능 구현

### ISSUE THREAD

**Issue by dayannne** [MusicDigging/Mudig_FE#59]
## 📝 Description
간단한 설명 작성

## 🔨 To-do
- [x] 각 페이지 Link 태그로 state 데이터 보내고 useLocation으로 받기
- [x] 이전 버튼 생성에 따른 페이지 전환 애니메이션 수정 (이전 버튼 클릭 시 왼쪽->오른쪽)(다음 버튼 클릭 시 오른쪽->왼쪽)
- [x] CreateNewPlaylist3 페이지 컴포넌트에서 useMutation 적용, POST API 요청

## 📌 참고 사항
