### ISSUE TITLE
메인 페이지 구현

### ISSUE THREAD

**Issue by yejify** [MusicDigging/Mudig_FE#6]
## 📝 Description
메인페이지 구현

## 🔨 To-do
- [x] 헤더
- [x] 나를 위한 추천
- [x] 인기 플리 리스트
- [x] 신규 플리 리스트
- [x] 내 플리 리스트
- [x] 네비게이션바

## 📌 참고 사항
![메인(최종)](https://github.com/MusicDigging/Mudig_FE/assets/116805856/17fd644d-836e-4846-a821-eeb84f9511d5)
