### ISSUE TITLE
이벤트 페이지 기능구현

### ISSUE THREAD

**Issue by yejify** [MusicDigging/Mudig_FE#60]
## 📝 Description
이벤트 플리 생성 페이지 기능 구현

## 🔨 To-do
- [x]  사용자 입력 값 100자 이내로 제한
- [x]  페이지 닫을 때 홈 페이지로 이동
- [x]  생성버튼 클릭 시 생성 로딩 페이지 이동 후 생성 요약으로 이동

## 📌 참고 사항
참고한 블로그 또는 사진 첨부

**Comment by yejify** [comment]
서버 에러로 API 통신은 코드만 구현했습니다
백엔드에서 로컬로 테스트 할 때 정상 작동하는데 서버에서만 에러가 난다고 답변 받았습니다!
![스크린샷 2023-12-06 오후 10 46 19](https://github.com/MusicDigging/Mudig_FE/assets/116805856/360c9923-f712-442a-a1ab-9ececd4cbd6d)
