### ISSUE TITLE
홈 페이지 기능 구현

### ISSUE THREAD

**Issue by yejify** [MusicDigging/Mudig_FE#61]
## 📝 Description
홈 페이지 기능 구현

## 🔨 To-do
- [x]  추천 플리 데이터 가져오기
- [x]  인기 순위 플리 데이터 가져오기
- [x]  신규 플리 데이터 가져오기
- [x]  유저 생성 플리 데이터 가져오기
- [x] 유저 생성 플리 더보기 링크 연결
- [x] nav bar 링크 연결
- [x] 검색 버튼과 검색 페이지 링크 연결

2차
- [x] 유저 정보 연결
- [x] 스플래쉬 페이지 이동
## 📌 참고 사항
참고한 블로그 또는 사진 첨부
