### ISSUE TITLE
생성 요약 페이지 기능 구현

### ISSUE THREAD

**Issue by easyxxu** [MusicDigging/Mudig_FE#69]
## 📝 Description
생성 요약 페이지 기능 구현

## 🔨 To-do
- [x]  플리 생성 시 결과 -> 생성 요약 페이지에 반영
- [x]  확인 버튼 클릭 시 플리 상세 페이지로 이동
- [ ] 플리 요약페이지 -> 플리 상세페이지 이동한 경우 다시 뒤로가기 못하도록 하기
