### ISSUE TITLE
프로필 페이지 구현

### ISSUE THREAD

**Issue by dayannne** [MusicDigging/Mudig_FE#8]
## 📝 Description
프로필 페이지 UI 구현하기

## 🔨 To-do
- [x] 이미지 공통 컴포넌트화 (프로필 이미지, 플레이리스트 이미지)
- [x] 플레이리스트/팔로잉/팔로워
- [x] 소개글 
- [x]  플레이리스트 공통 컴포넌트화
- [x] 대표 플레이리스트 테이블 삽입 
- [x] 더보기 버튼 클릭시 미니모달 오픈

## 📌 참고 사항
![마이프로필](https://github.com/MusicDigging/Mudig_FE/assets/105140201/3e9d2f82-7b8a-4f81-bb54-bd8e19ac4e4b)
