### ISSUE TITLE
유저정보부분 확인 

### ISSUE THREAD

**Issue by junny97** [MusicDigging/Mudig_FE#86]
## 📝 Description
로그인, 회원가입, 프로필 설정과 관련된 유저정보 부분에서 버그나 누락된 부분을 찾고 수정합니다.

## 🔨 To-do
- [x]  userInfo Atom에서 비밀번호 정보 회원가입 post 요청때까지만 관리하고 로그인 이후엔 삭제
- [x] 회원가입 이메일 인증 중 이미 가입된 이메일이라면 '이미 가입된 이메일입니다' 유효성 검사 추가하기 
- [x]  css 스타일 확인 및 수정

## 📌 참고 사항
참고한 블로그 또는 사진 첨부
